---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all_hosts
  remote_user: ansible
  # remote_user: user
  #sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
