---
- name: Start  instances
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    instance_ids:
      - 'i-XXXXXXXX'
  ec2_region: us-east-1
  tasks:
    - name: Start the feature instances
      ec2:
        instance_ids: '{{ instance_ids }}'
        ec2_region: '{{ ec2_region }}'
        state: running
        wait: True
